# Generated by Django 5.2.3 on 2025-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
