# Generated by Django 5.2.3 on 2025-07-07 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clientsmodel_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientsModel',
            new_name='Clients',
        ),
    ]
