# Generated by Django 5.2.4 on 2025-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_categorie_alter_recipe_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
