services:
  db:
    image: postgres:15
    container_name: django_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: my_user_blog
      POSTGRES_PASSWORD: z{IC7M87K*Pz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
